<a href="https://colab.research.google.com/github/qudrat70/data-analysis-Numpy-kutubxonasi/blob/main/Array_(massiv)_o'qlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

*Bismillah*

In [2]:
Q = np.arange(6)
Q

array([0, 1, 2, 3, 4, 5])

In [5]:
Q = np.arange(6).reshape(3,2)
Q

array([[0, 1],
       [2, 3],
       [4, 5]])

Q.T # A massivning Trasnpose ko'rinishi beradi

In [17]:
Q.T

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
X = np.arange(12)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
X = np.arange(12).reshape(4,3)
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
X.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

# X.swapaxes() # A massivning Transpose ko'rinishi beradi

In [16]:
X.swapaxes(1,0)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [18]:
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
X.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

np.dot(X,X.T) # XX^T hosil bo'lgan massiv

In [22]:
np.dot(X, X.T)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])