<a href="https://colab.research.google.com/github/qudrat70/data-analysis-Numpy-kutubxonasi/blob/main/Bolean_Indekslash_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
names = np.array(['Qudrat',"Navro'z",'Umrbek','Davron','Otabek','Shohruh','Elyor','Qudrat','Jasurbek',"Navro'z"])
names

array(['Qudrat', "Navro'z", 'Umrbek', 'Davron', 'Otabek', 'Shohruh',
       'Elyor', 'Qudrat', 'Jasurbek', "Navro'z"], dtype='<U8')

In [4]:
data = np.random.randn(10,5)
data

array([[-2.12568106,  0.62291643, -2.50381156, -0.19549846, -0.28194256],
       [-1.90079971, -0.25527905, -0.65334879,  1.36572102, -0.26012187],
       [-1.5241736 ,  0.03693181, -1.14294597, -1.00137935,  1.13778881],
       [-1.37581456, -0.84283856,  1.07103035,  0.73818379,  1.89119481],
       [ 0.83035596, -1.03681883, -0.79306272, -2.97342807, -0.32398078],
       [ 1.18214396, -0.35815029,  0.90880317, -2.03087495, -0.09724448],
       [ 1.72566286, -1.78735814, -0.36780511,  0.44765131, -1.04245359],
       [-0.31817615, -0.12581493,  1.88440342, -0.40216682, -0.02271173],
       [-1.18348875, -0.52542809,  1.07039811,  0.11162139,  0.73841143],
       [-0.05343197, -0.54972217,  0.34241495, -1.91754623, -1.17070533]])

In [6]:
names == "Qudrat"

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [8]:
data[names=="Qudrat"]

array([[-2.12568106,  0.62291643, -2.50381156, -0.19549846, -0.28194256],
       [-0.31817615, -0.12581493,  1.88440342, -0.40216682, -0.02271173]])

In [9]:
data[names == "Navro'z"]

array([[-1.90079971, -0.25527905, -0.65334879,  1.36572102, -0.26012187],
       [-0.05343197, -0.54972217,  0.34241495, -1.91754623, -1.17070533]])

In [10]:
data[names != "Umrbek"]

array([[-2.12568106,  0.62291643, -2.50381156, -0.19549846, -0.28194256],
       [-1.90079971, -0.25527905, -0.65334879,  1.36572102, -0.26012187],
       [-1.37581456, -0.84283856,  1.07103035,  0.73818379,  1.89119481],
       [ 0.83035596, -1.03681883, -0.79306272, -2.97342807, -0.32398078],
       [ 1.18214396, -0.35815029,  0.90880317, -2.03087495, -0.09724448],
       [ 1.72566286, -1.78735814, -0.36780511,  0.44765131, -1.04245359],
       [-0.31817615, -0.12581493,  1.88440342, -0.40216682, -0.02271173],
       [-1.18348875, -0.52542809,  1.07039811,  0.11162139,  0.73841143],
       [-0.05343197, -0.54972217,  0.34241495, -1.91754623, -1.17070533]])

In [11]:
data[~(names == 'Umrbek')]

array([[-2.12568106,  0.62291643, -2.50381156, -0.19549846, -0.28194256],
       [-1.90079971, -0.25527905, -0.65334879,  1.36572102, -0.26012187],
       [-1.37581456, -0.84283856,  1.07103035,  0.73818379,  1.89119481],
       [ 0.83035596, -1.03681883, -0.79306272, -2.97342807, -0.32398078],
       [ 1.18214396, -0.35815029,  0.90880317, -2.03087495, -0.09724448],
       [ 1.72566286, -1.78735814, -0.36780511,  0.44765131, -1.04245359],
       [-0.31817615, -0.12581493,  1.88440342, -0.40216682, -0.02271173],
       [-1.18348875, -0.52542809,  1.07039811,  0.11162139,  0.73841143],
       [-0.05343197, -0.54972217,  0.34241495, -1.91754623, -1.17070533]])

In [12]:
print(names)
print(data)

['Qudrat' "Navro'z" 'Umrbek' 'Davron' 'Otabek' 'Shohruh' 'Elyor' 'Qudrat'
 'Jasurbek' "Navro'z"]
[[-2.12568106  0.62291643 -2.50381156 -0.19549846 -0.28194256]
 [-1.90079971 -0.25527905 -0.65334879  1.36572102 -0.26012187]
 [-1.5241736   0.03693181 -1.14294597 -1.00137935  1.13778881]
 [-1.37581456 -0.84283856  1.07103035  0.73818379  1.89119481]
 [ 0.83035596 -1.03681883 -0.79306272 -2.97342807 -0.32398078]
 [ 1.18214396 -0.35815029  0.90880317 -2.03087495 -0.09724448]
 [ 1.72566286 -1.78735814 -0.36780511  0.44765131 -1.04245359]
 [-0.31817615 -0.12581493  1.88440342 -0.40216682 -0.02271173]
 [-1.18348875 -0.52542809  1.07039811  0.11162139  0.73841143]
 [-0.05343197 -0.54972217  0.34241495 -1.91754623 -1.17070533]]


In [14]:
mask = (names == "Davron") | (names == "Otabek")
mask

array([False, False, False,  True,  True, False, False, False, False,
       False])

In [15]:
data[mask]

array([[-1.37581456, -0.84283856,  1.07103035,  0.73818379,  1.89119481],
       [ 0.83035596, -1.03681883, -0.79306272, -2.97342807, -0.32398078]])

In [16]:
data

array([[-2.12568106,  0.62291643, -2.50381156, -0.19549846, -0.28194256],
       [-1.90079971, -0.25527905, -0.65334879,  1.36572102, -0.26012187],
       [-1.5241736 ,  0.03693181, -1.14294597, -1.00137935,  1.13778881],
       [-1.37581456, -0.84283856,  1.07103035,  0.73818379,  1.89119481],
       [ 0.83035596, -1.03681883, -0.79306272, -2.97342807, -0.32398078],
       [ 1.18214396, -0.35815029,  0.90880317, -2.03087495, -0.09724448],
       [ 1.72566286, -1.78735814, -0.36780511,  0.44765131, -1.04245359],
       [-0.31817615, -0.12581493,  1.88440342, -0.40216682, -0.02271173],
       [-1.18348875, -0.52542809,  1.07039811,  0.11162139,  0.73841143],
       [-0.05343197, -0.54972217,  0.34241495, -1.91754623, -1.17070533]])

In [21]:
data[data<0] = 0
data

array([[0.        , 0.62291643, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.36572102, 0.        ],
       [0.        , 0.03693181, 0.        , 0.        , 1.13778881],
       [0.        , 0.        , 1.07103035, 0.73818379, 1.89119481],
       [0.83035596, 0.        , 0.        , 0.        , 0.        ],
       [1.18214396, 0.        , 0.90880317, 0.        , 0.        ],
       [1.72566286, 0.        , 0.        , 0.44765131, 0.        ],
       [0.        , 0.        , 1.88440342, 0.        , 0.        ],
       [0.        , 0.        , 1.07039811, 0.11162139, 0.73841143],
       [0.        , 0.        , 0.34241495, 0.        , 0.        ]])