<a href="https://colab.research.google.com/github/qudrat70/data-analysis-Numpy-kutubxonasi/blob/main/indexlash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10,100,10)
arr[2]

30

In [ ]:
arr[-2]

80

In [ ]:
arr[3:]

array([40, 50, 60, 70, 80, 90])

In [ ]:
arr[0]

10

In [ ]:
arr[:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[3:5]

array([40, 50])

In [ ]:
sliced_arr=arr[3:5]
sliced_arr[:]=0
sliced_arr

array([0, 0])

In [ ]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

*2 o'lchamli (2d array) massivlarda indeks va kesib olish*

In [ ]:
arr2d = np.array([[1,2,4,],[4,6,9,],[4,10,5]])
arr2d

array([[ 1,  2,  4],
       [ 4,  6,  9],
       [ 4, 10,  5]])

In [ ]:
arr2d

9

In [ ]:
arr2d[2,2]

5

In [ ]:
sl_arr2d = arr2d[1,(1,2)]
sl_arr2d

array([6, 9])

In [ ]:
sl_arr2d = arr2d[:2]
sl_arr2d

array([[1, 2, 4],
       [4, 6, 9]])

In [ ]:
sl_arr2d = arr2d[:2,1:]
sl_arr2d

array([[2, 4],
       [6, 9]])

In [ ]:
sl_arr2d = arr2d[2]
sl_arr2d

array([ 4, 10,  5])

In [ ]:
sl_arr2d = arr2d[2,:]
sl_arr2d

array([ 4, 10,  5])

In [ ]:
sl_arr2d = arr2d[2:,:]
sl_arr2d

array([[ 4, 10,  5]])

In [ ]:
sl_arr2d = arr2d[:,:2]
sl_arr2d

array([[ 1,  2],
       [ 4,  6],
       [ 4, 10]])

In [ ]:
sl_arr2d = arr2d[1,:2]
sl_arr2d

array([4, 6])

In [ ]:
sl_arr2d = arr2d[1:2,:2]
sl_arr2d

array([[4, 6]])

In [ ]:
arr3d = np.array([[[2,4,5,],
                   [4,6,10],
                   [4,12,11]],
                   
                   [[3,7,14],
                    [67,45,21],
                    [14,63,89]],
                    
                    [[67,23,90],
                     [56,34,89],
                     [23,89,34]]])
arr3d

array([[[ 2,  4,  5],
        [ 4,  6, 10],
        [ 4, 12, 11]],

       [[ 3,  7, 14],
        [67, 45, 21],
        [14, 63, 89]],

       [[67, 23, 90],
        [56, 34, 89],
        [23, 89, 34]]])

In [ ]:
arr3d[0][2,1]

12

In [ ]:
arr3d[2][1,1:]

array([34, 89])